### ISSUE TITLE
[bug]: improve crashlogs during connection failures

### ISSUE THREAD

**Issue by slayerjain** [keploy/java-sdk#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The program throws null pointer exception if keploy server is unavailable. 

```
2022-09-09 16:03:27.169  WARN 76409 --- [       Thread-2] io.keploy.service.GrpcService            : RPC failed: Status{code=UNAVAILABLE, description=io exception, cause=io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:8081
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
	at io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
}
2022-09-09 16:03:27.170 ERROR 76409 --- [       Thread-2] io.keploy.servlet.middleware             : failed to run tests

java.lang.NullPointerException: null
	at io.keploy.service.GrpcService.Test(GrpcService.java:232) ~[keploy-sdk-1.0.13.jar:na]
	at io.keploy.servlet.middleware.lambda$init$0(middleware.java:93) ~[keploy-sdk-1.0.13.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2022-09-09 16:03:27.186  INFO 76409 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-09-09 16:03:27.187  INFO 76409 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-09-09 16:03:27.190  INFO 76409 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.


```

### Steps to reproduce

1. Integrate Java SDK with any application
2. Start in test mode without starting keploy. 

### Version

Local

**Comment by Sarthak160** [comment]
Closed by #48
